### PR TITLE
Use EJSON.parse

### PR DESCRIPTION
**Pull request by benmgreene**
Because why not :-)

https://github.com/meteor/meteor/blob/master/packages/ejson/ejson.js#L345

### CODE REVIEW

**Comment by arunoda** [comment]
Yeah! Why not?

BTW: Could you check when it's landed to Meteor? Was it there before 1.0 ?

**Comment by benmgreene** [comment]
Sure — looks like it’s been there for a long while :-)

https://github.com/meteor/meteor/blame/master/packages/ejson/ejson.js#L345 https://github.com/meteor/meteor/blame/master/packages/ejson/ejson.js#L345

**Comment by arunoda** [comment]
Okay. Looks good to me :)

**Comment by arunoda** [comment]
Published as: `v1.4.1`

**Pull request merged**
